spring:
  datasource:
    url: jdbc:mysql://10.1.0.167:3306/mysql
    username: root
    password: rootbamboo
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl.auto: none
  multipart:  
    enabled: true  
    max-file-size: 50mb  
    max-request-size: 50mb
  thread-pool:
    corePoolSize: 5
    maxPoolSize: 20
    keepAliveSeconds: 600
    queueCapacity: 50
    threadNamePrefix: AsyncPool-
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

